package:
  name: skeletopyze
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}
  version: {{tagged_version}}

source:
  path: ..

build:
  number: 1
  string: py_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
 build:
   - cmake
   - gcc
   - boost >=1.6
   - python
   - numpy
   - vigra
 run:
   - libgcc
   - boost >=1.6
   - python
   - numpy
   - vigra

about:
  home: https://github.com/funkey/skeletopyze
  license: MIT License
